spring:
    profiles:
        active: prod
    data:
        mongodb:
            host: ds143449.mlab.com
            port: 43449
            database: heroku_l74bpd51
            username: jojeps
            password: jojeps